// HTML/CSS 単語帳データ

const HTML_CARDS = [
  { id:"div", tag:"div", group:"構造化", meaning:"汎用的な箱。それ自体には意味を持たず、レイアウトのグループ化に使う。", usage:'<div class="box">...</div>', note:"意味を持たないので、可能ならsection/article/header等の意味のあるタグを優先する。" },
  { id:"section", tag:"section", group:"構造化", meaning:"ページ内の意味のあるまとまり(章・節)を表す。", usage:"<section>\n  <h2>会社概要</h2>\n</section>", note:"見出し(h1〜h6)とセットで使うのが基本。" },
  { id:"p", tag:"p", group:"テキスト", meaning:"段落。ひとまとまりの文章を表す。", usage:"<p>本文がここに入ります。</p>", note:"p要素の中に他のブロック要素(div等)は入れられない。" },
  { id:"a", tag:"a", group:"リンク/メディア", meaning:"他のページやページ内の場所へのリンクを作る。", usage:'<a href="https://example.com">サイトへ</a>', note:"href属性がないと単なる文字装飾になり、リンクとして機能しない。", answer:["a","href"] },
  { id:"img", tag:"img", group:"リンク/メディア", meaning:"画像を表示する。閉じタグを持たない空要素。", usage:'<img src="cat.jpg" alt="猫の写真">', note:"alt属性は必須。画像が読み込めない時の代替や読み上げに使われる。", answer:["img","alt"] },
  { id:"h1", tag:"h1", group:"テキスト", meaning:"ページの中で最も重要な大見出し。", usage:"<h1>ページタイトル</h1>", note:"1ページに1つが基本(SEO・アクセシビリティ上の理由)。" },
  { id:"h2", tag:"h2", group:"テキスト", meaning:"h1の次の階層の中見出し。", usage:"<h2>セクション名</h2>", note:"見出しレベルは飛び番(h1の次にh3など)にしない。" },
  { id:"span", tag:"span", group:"テキスト", meaning:"文章の一部だけを装飾・指定するためのインライン要素。", usage:'<span class="highlight">重要</span>', note:"それ自体に意味はなく、CSSやJSでピンポイントに指定するために使う。" },
  { id:"header", tag:"header", group:"構造化", meaning:"ページやセクションの先頭部分(ロゴ・タイトル・ナビ等)。", usage:"<header>...</header>", note:"ページ全体だけでなく、section内など複数箇所で使える。" },
  { id:"footer", tag:"footer", group:"構造化", meaning:"フッター部分(著作権表示・連絡先等)。", usage:"<footer>...</footer>", note:"headerと同様、ページ/セクションどちらでも使用可。" },
  { id:"main", tag:"main", group:"構造化", meaning:"そのページの主要コンテンツを表す。", usage:"<main>...</main>", note:"1ページに1つだけ使う。" },
  { id:"nav", tag:"nav", group:"構造化", meaning:"ナビゲーション(主要な移動リンク)のまとまり。", usage:"<nav><a>Home</a><a>About</a></nav>", note:"すべてのリンクをnavにする必要はなく、主要な導線のみに使う。" },
  { id:"ul", tag:"ul", group:"リスト", meaning:"順序を持たない箇条書きリスト。", usage:"<ul>\n  <li>項目1</li>\n</ul>", note:"直下の子要素はliのみが基本。" },
  { id:"li", tag:"li", group:"リスト", meaning:"リストの1項目を表す。", usage:"<li>項目</li>", note:"ulまたはolの中でのみ使う。" },
  { id:"button", tag:"button", group:"フォーム", meaning:"クリック可能なボタン。", usage:'<button type="button">送信</button>', note:"type属性を省略するとフォーム内でsubmit扱いになるので注意。" },
  { id:"form", tag:"form", group:"フォーム", meaning:"ユーザー入力を送信するための領域。", usage:'<form action="/submit" method="post">...</form>', note:"action=送信先、method=送信方法(get/post)を指定する。" },
  { id:"input", tag:"input", group:"フォーム", meaning:"1行の入力欄。type属性で種類が変わる。", usage:'<input type="text" name="name">', note:"typeでtext/email/checkbox等、様々な入力形式に切り替えられる。" },
  { id:"label", tag:"label", group:"フォーム", meaning:"入力項目の説明ラベル。", usage:'<label for="name">名前</label>\n<input id="name">', note:"for属性とinputのidを一致させると、ラベルクリックで入力欄にフォーカスできる。" },
  { id:"h3", tag:"h3", group:"テキスト", meaning:"h2のさらに下の階層の小見出し。", usage:"<h3>...</h3>", note:"見出しの階層構造(h1→h2→h3)を飛ばさないようにする。" },
  { id:"br", tag:"br", group:"テキスト", meaning:"改行を挿入する空要素。", usage:"1行目<br>2行目", note:"レイアウト目的での多用は非推奨。余白調整はCSSのmarginで行う。" },
  { id:"strong", tag:"strong", group:"テキスト", meaning:"重要な文字を太字で強調する。", usage:"<strong>重要</strong>", note:"見た目だけでなく「意味的に重要」というニュアンスを持つ。" },
  { id:"article", tag:"article", group:"構造化", meaning:"それ単体で完結する記事・投稿を表す。", usage:"<article>\n  <h2>記事タイトル</h2>\n</article>", note:"ブログ記事やニュース1件など、単独で意味が通る内容に使う。" },
  { id:"aside", tag:"aside", group:"構造化", meaning:"本文に関連する補足情報(サイドバー等)を表す。", usage:"<aside>関連リンク</aside>", note:"本文と直接関係ない広告などには使わない。" },
  { id:"table", tag:"table", group:"表", meaning:"表(テーブル)を作る。", usage:"<table>...</table>", note:"レイアウト目的の使用は非推奨。あくまで表形式データ用。" },
  { id:"tr", tag:"tr", group:"表", meaning:"表の1行(table row)を表す。", usage:"<tr><td>...</td></tr>", note:"thead/tbody内に置くとより構造が明確になる。" },
  { id:"td", tag:"td", group:"表", meaning:"表のデータセル。", usage:"<td>データ</td>", note:"見出し用のセルにはthを使う。" },
  { id:"th", tag:"th", group:"表", meaning:"表の見出しセル。", usage:"<th>項目名</th>", note:"scope属性で行/列どちらの見出しかを明示できる。" },
  { id:"textarea", tag:"textarea", group:"フォーム", meaning:"複数行にわたる入力欄。", usage:'<textarea rows="4"></textarea>', note:"初期値はvalue属性ではなく、開始タグと終了タグの間に書く。" },
  { id:"select", tag:"select", group:"フォーム", meaning:"ドロップダウン形式の選択欄。", usage:"<select><option>A</option></select>", note:"中に複数のoptionを並べて選択肢を作る。" },
  { id:"option", tag:"option", group:"フォーム", meaning:"selectの中の1つの選択肢。", usage:'<option value="a">A</option>', note:"value属性が送信される値、タグ内のテキストは画面表示用。" },
  { id:"video", tag:"video", group:"リンク/メディア", meaning:"動画を埋め込む。", usage:'<video src="movie.mp4" controls></video>', note:"controls属性を付けると再生ボタン等のUIが表示される。" },
  { id:"iframe", tag:"iframe", group:"リンク/メディア", meaning:"別のページ・別サイトをページ内に埋め込む。", usage:'<iframe src="https://example.com"></iframe>', note:"外部サイトの埋め込みはセキュリティ設定に注意が必要。" },
  { id:"meta", tag:"meta", group:"ページ設定", meaning:"文字コードやビューポートなど、ページの情報を設定する。", usage:'<meta charset="UTF-8">', note:"head内に書き、画面には表示されない。" },
  { id:"title", tag:"title", group:"ページ設定", meaning:"ブラウザのタブに表示されるページタイトル。", usage:"<title>ページ名</title>", note:"SEOにも影響する重要なタグ。" },
  { id:"link", tag:"link", group:"ページ設定", meaning:"外部CSSファイルなどを読み込む。", usage:'<link rel="stylesheet" href="style.css">', note:'rel="stylesheet"の指定を忘れないこと。' },
  { id:"head", tag:"head", group:"ページ設定", meaning:"メタ情報や各種設定をまとめる部分。画面には表示されない。", usage:"<head>...</head>", note:"title/meta/linkなどをここに入れる。" },
  { id:"body", tag:"body", group:"ページ設定", meaning:"実際に画面に表示される内容全体。", usage:"<body>...</body>", note:"見た目に関わる要素はすべてこの中に書く。" },
  { id:"html", tag:"html", group:"ページ設定", meaning:"HTML文書全体を囲むルート要素。", usage:'<html lang="ja">...</html>', note:"lang属性で言語を指定する(日本語なら\"ja\")。" },
  { id:"figure", tag:"figure", group:"リンク/メディア", meaning:"画像とその説明(キャプション)をセットで扱う。", usage:"<figure>\n  <img src=\"cat.jpg\" alt=\"猫\">\n  <figcaption>猫の写真</figcaption>\n</figure>", note:"figcaptionと組み合わせて使うことが多い。" },
  { id:"small", tag:"small", group:"テキスト", meaning:"注釈や免責事項など、補足的な文章を表す。", usage:"<small>※価格は税込です</small>", note:"単に文字を小さくしたいだけならCSSのfont-sizeを使う。" },
];

const CSS_CARDS = [
  { id:"display", tag:"display", group:"レイアウト", meaning:"要素の表示形式を決める(block/inline/flex/grid/none等)。", usage:"display: flex;", note:"display: none; は要素を非表示にし、レイアウトからも除外する。" },
  { id:"width", tag:"width", group:"サイズ", meaning:"要素の幅を指定する。", usage:"width: 300px;", note:"%で指定すると親要素に対する割合になる。" },
  { id:"height", tag:"height", group:"サイズ", meaning:"要素の高さを指定する。", usage:"height: 200px;", note:"中身がheightを超えるとoverflowが発生する。" },
  { id:"margin", tag:"margin", group:"余白", meaning:"要素の外側の余白。", usage:"margin: 16px;", note:"margin: 0 auto; で要素を左右中央寄せできる。" },
  { id:"padding", tag:"padding", group:"余白", meaning:"要素の内側の余白(枠線の内側)。", usage:"padding: 12px 16px;", note:"背景色はpadding部分にも適用される。" },
  { id:"color", tag:"color", group:"テキスト", meaning:"文字の色を指定する。", usage:"color: #333;", note:"背景色とのコントラスト比に注意する(可読性)。" },
  { id:"font-size", tag:"font-size", group:"テキスト", meaning:"文字の大きさを指定する。", usage:"font-size: 16px;", note:"remを使うとユーザーのブラウザ設定に応じて拡大縮小できる。" },
  { id:"background", tag:"background", group:"背景/装飾", meaning:"背景に関する設定をまとめて指定できるショートハンド。", usage:"background: #fff url(bg.png) no-repeat;", note:"個別指定(background-color等)の方が読みやすい場合も多い。" },
  { id:"background-color", tag:"background-color", group:"背景/装飾", meaning:"背景色を指定する。", usage:"background-color: #ff8a65;", note:"半透明にしたい場合はrgba()を使う。" },
  { id:"font-weight", tag:"font-weight", group:"テキスト", meaning:"文字の太さを指定する。", usage:"font-weight: bold;", note:"数値指定(400=標準, 700=太字)も可能。" },
  { id:"line-height", tag:"line-height", group:"テキスト", meaning:"行の高さ(行間)を指定する。", usage:"line-height: 1.6;", note:"単位なしの数値がfont-sizeに対する倍率として推奨される。" },
  { id:"flex", tag:"flex", group:"Flex/Grid", meaning:"flexアイテムの伸縮比率などをまとめて指定する。", usage:"flex: 1;", note:"flex-grow/flex-shrink/flex-basisのショートハンド。" },
  { id:"justify-content", tag:"justify-content", group:"Flex/Grid", meaning:"flex/gridコンテナ内の主軸方向(横方向)の配置を指定する。", usage:"justify-content: space-between;", note:"親要素にdisplay: flex; が必要。" },
  { id:"align-items", tag:"align-items", group:"Flex/Grid", meaning:"flex/gridコンテナ内の交差軸方向(縦方向)の配置を指定する。", usage:"align-items: center;", note:"個別要素だけずらしたい場合はalign-selfを使う。" },
  { id:"position", tag:"position", group:"位置/重なり", meaning:"要素の配置方法を指定する(static/relative/absolute/fixed/sticky)。", usage:"position: relative;", note:"absoluteは直近のposition指定済み祖先要素を基準に配置される。" },
  { id:"top", tag:"top", group:"位置/重なり", meaning:"position指定時の上からの位置。", usage:"top: 0;", note:"position: static; のままでは効かない。" },
  { id:"left", tag:"left", group:"位置/重なり", meaning:"position指定時の左からの位置。", usage:"left: 10px;", note:"topと同様、position指定が前提となる。" },
  { id:"right", tag:"right", group:"位置/重なり", meaning:"position指定時の右からの位置。", usage:"right: 0;", note:"leftとrightを両方指定すると幅が自動計算されることがある。" },
  { id:"bottom", tag:"bottom", group:"位置/重なり", meaning:"position指定時の下からの位置。", usage:"bottom: 20px;", note:"フッター固定などのレイアウトでよく使う。" },
  { id:"border", tag:"border", group:"背景/装飾", meaning:"要素の枠線(太さ・線種・色)を指定する。", usage:"border: 1px solid #ccc;", note:"border-radiusと組み合わせて丸みのある枠にできる。" },
  { id:"border-radius", tag:"border-radius", group:"背景/装飾", meaning:"要素の角を丸くする。", usage:"border-radius: 12px;", note:"50%を指定すると正方形の要素が円になる。" },
  { id:"box-shadow", tag:"box-shadow", group:"背景/装飾", meaning:"要素に影をつける。", usage:"box-shadow: 0 4px 10px rgba(0,0,0,0.1);", note:"値は(横方向, 縦方向, ぼかし, 色)の順で指定する。" },
  { id:"text-align", tag:"text-align", group:"テキスト", meaning:"テキストの水平方向の揃え位置を指定する。", usage:"text-align: center;", note:"ブロック要素自体ではなく、中の文字を揃えるプロパティ。" },
  { id:"font-family", tag:"font-family", group:"テキスト", meaning:"使用するフォントを指定する。", usage:'font-family: "Helvetica", sans-serif;', note:"複数指定し、最後にsans-serif等の総称フォントを置くのが基本。" },
  { id:"letter-spacing", tag:"letter-spacing", group:"テキスト", meaning:"文字と文字の間隔を指定する。", usage:"letter-spacing: 0.05em;", note:"見出しの文字間を少し広げると読みやすくなることが多い。" },
  { id:"opacity", tag:"opacity", group:"背景/装飾", meaning:"要素全体の透明度(0〜1)を指定する。", usage:"opacity: 0.5;", note:"0にしても見えなくなるだけでクリック判定は残る(display: noneとの違い)。" },
  { id:"overflow", tag:"overflow", group:"レイアウト", meaning:"要素からはみ出た内容の扱いを指定する。", usage:"overflow: hidden;", note:"overflow: scroll; にするとスクロールバーを表示できる。" },
  { id:"grid", tag:"grid", group:"Flex/Grid", meaning:"グリッドレイアウトを有効にするショートハンド。", usage:"display: grid;", note:"通常display: grid;とセットで使う。" },
  { id:"grid-template-columns", tag:"grid-template-columns", group:"Flex/Grid", meaning:"グリッドの列の数と幅を指定する。", usage:"grid-template-columns: repeat(3, 1fr);", note:"frは残りのスペースを均等に分ける単位。" },
  { id:"gap", tag:"gap", group:"Flex/Grid", meaning:"flex/gridの要素間の間隔を指定する。", usage:"gap: 16px;", note:"marginと違い、並びの外側の端には余白がつかない。" },
  { id:"z-index", tag:"z-index", group:"位置/重なり", meaning:"要素の重なり順を指定する。", usage:"z-index: 10;", note:"position: static; の要素には効かない。数値が大きいほど手前になる。" },
  { id:"transform", tag:"transform", group:"アニメーション", meaning:"要素を移動・回転・拡大縮小する。", usage:"transform: rotate(10deg);", note:"レイアウトに影響を与えずに見た目だけ変形できる。" },
  { id:"transition", tag:"transition", group:"アニメーション", meaning:"プロパティの変化を滑らかにアニメーションさせる。", usage:"transition: all 0.3s ease;", note:"hover等の状態変化と組み合わせて使うことが多い。" },
  { id:"cursor", tag:"cursor", group:"その他", meaning:"マウスカーソルの形状を指定する。", usage:"cursor: pointer;", note:"クリック可能な要素にpointerを指定するとユーザーに伝わりやすい。" },
  { id:"list-style", tag:"list-style", group:"背景/装飾", meaning:"リストのマーカー(・や数字)の見た目を指定する。", usage:"list-style: none;", note:"noneにするとマーカーが消え、独自デザインのリストが作りやすくなる。" },
  { id:"object-fit", tag:"object-fit", group:"背景/装飾", meaning:"画像や動画を枠に収める際の比率調整を指定する。", usage:"object-fit: cover;", note:"coverは枠を埋めるようにトリミング、containは全体が収まるように縮小する。" },
  { id:"max-width", tag:"max-width", group:"サイズ", meaning:"要素の最大幅を指定する。", usage:"max-width: 100%;", note:"レスポンシブ対応の基本(画像がはみ出さないようにする等)。" },
  { id:"min-height", tag:"min-height", group:"サイズ", meaning:"要素の最低の高さを指定する。", usage:"min-height: 100vh;", note:"中身が少なくても画面いっぱいの高さを確保したい時に使う。" },
  { id:"media", tag:"@media", group:"レスポンシブ", meaning:"画面幅などの条件によってCSSを切り替える。", usage:"@media (max-width: 600px) {\n  .box { display: block; }\n}", note:"レスポンシブデザインの基本。ブレークポイントごとに指定する。" },
  { id:"animation", tag:"animation", group:"アニメーション", meaning:"キーフレームを使った複雑なアニメーションを設定する。", usage:"animation: fadeIn 1s ease;", note:"@keyframesで動きの中身を別途定義する必要がある。" },
];

const SECTIONS = {
  html: { label: "HTML", cards: HTML_CARDS },
  css: { label: "CSS", cards: CSS_CARDS },
};
